In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/weather.csv'

df = pd.read_csv(file_path)
print(df.head())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch      last_updated  temperature_celsius  \
0          1715849100  2024-05-16 13:15                 26.6
1          1715849100  2024-05-16 10:45                 19.0
2          1715849100  2024-05-16 09:45                 23.0
3          1715849100  2024-05-16 10:45                  6.3
4          1715849100  2024-05-16 09:45                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                    79.8  Partly Cloudy  ...                8.4
1                    66.2  Partly cloudy  ...                1.1
2                    73.4          Sunny  ...               10.4
3                    43.3  Light drizzle  ...                0.7
4                    78.8  Partly cloudy  ...              183.4

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0              26.6                         1                          1
1               2.0                         1                          1
2              18.4                         1                          1
3               0.9                         1                          1
4             262.3                         5                         10

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous                 55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous                 55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous                 55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous                 55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous                 55

[5 rows x 41 columns]

In [ ]:

# Step 3: Inspect Data Structure, Data Types, and Key Variables
print(" Dataset Shape:", df.shape)
print("\n Data Info:")
df.info()
print("\n Summary Statistics (numeric columns):")
display(df.describe())
print("\n Data Types:")
print(df.dtypes)

 Dataset Shape: (88273, 41)

 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88273 entries, 0 to 88272
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       88273 non-null  object
 1   location_name                 88273 non-null  object
 2   latitude                      88273 non-null  float64
 3   longitude                     88273 non-null  float64
 4   timezone                      88273 non-null  object
 5   last_updated_epoch            88273 non-null  int64
 6   last_updated                  88273 non-null  object
 7   temperature_celsius           88273 non-null  float64
 8   temperature_fahrenheit        88273 non-null  float64
 9   condition_text                88273 non-null  object
 10  wind_mph                      88273 non-null  float64
 11  wind_kph                      88273 non-null  float64
 12  wind_degree                   88273 non-null  int64
 13  wind_direction                88273 non-null  object
 14  pressure_mb                   88273 non-null  float64
 15  pressure_in                   88273 non-null  float64
 16  precip_mm                     88273 non-null  float64
 17  precip_in                     88273 non-null  float64
 18  humidity                      88273 non-null  int64
 19  cloud                         88273 non-null  int64
 20  feels_like_celsius            88273 non-null  float64
 21  feels_like_fahrenheit         88273 non-null  float64
 22  visibility_km                 88273 non-null  float64
 23  visibility_miles              88273 non-null  float64
 24  uv_index                      88273 non-null  float64
 25  gust_mph                      88273 non-null  float64
 26  gust_kph                      88273 non-null  float64
 27  air_quality_Carbon_Monoxide   88273 non-null  float64
 28  air_quality_Ozone             88273 non-null  float64
 29  air_quality_Nitrogen_dioxide  88273 non-null  float64
 30  air_quality_Sulphur_dioxide   88273 non-null  float64
 31  air_quality_PM2.5             88273 non-null  float64
 32  air_quality_PM10              88273 non-null  float64
 33  air_quality_us-epa-index      88273 non-null  int64
 34  air_quality_gb-defra-index    88273 non-null  int64
 35  sunrise                       88273 non-null  object
 36  sunset                        88273 non-null  object
 37  moonrise                      88273 non-null  object
 38  moonset                       88273 non-null  object
 39  moon_phase                    88273 non-null  object
 40  moon_illumination             88273 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 27.6+ MB

 Summary Statistics (numeric columns):

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,88273.000000,88273.000000,8.827300e+04,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,...,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000,88273.000000
mean,19.125848,22.172647,1.735507e+09,22.681788,72.828923,8.292613,13.348916,170.584743,1013.966536,29.941799,...,18.752776,517.197758,63.691560,15.485259,11.320585,26.212169,54.275850,1.760504,2.770020,50.746616
std,24.470798,65.836668,1.135389e+07,9.091355,16.364215,8.137603,13.093950,103.107058,11.786522,0.348003,...,15.089616,860.151958,33.050899,25.964224,42.271465,41.510377,163.172827,0.988090,2.590155,35.125443
min,-41.300000,-175.200000,1.715849e+09,-24.900000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.725710e+09,18.000000,64.400000,4.000000,6.500000,82.000000,1010.000000,29.830000,...,10.700000,234.950000,43.000000,1.295000,0.800000,7.030000,10.490000,1.000000,1.000000,16.000000
50%,17.250000,23.316700,1.735555e+09,25.000000,77.000000,6.900000,11.200000,164.000000,1013.000000,29.920000,...,16.200000,327.100000,61.000000,4.440000,2.405000,14.985000,22.015000,1.000000,2.000000,52.000000
75%,40.400000,50.580000,1.745313e+09,28.400000,83.100000,11.400000,18.400000,257.000000,1017.000000,30.050000,...,24.800000,505.050000,81.000000,17.205000,9.065000,30.340000,46.990000,2.000000,3.000000,86.000000
max,64.150000,179.220000,1.755074e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

 Data Types:
country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                     float64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                float64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [ ]:
# Step 4: Missing Values, Anomalies & Data Coverage (short)
print(" Missing Values:", "None " if df.isnull().sum().sum()==0 else df.isnull().sum()[df.isnull().sum()>0])
print("Humidity anomalies:", len(df.query("humidity<0 or humidity>100")),
      "| Temperature anomalies:", len(df.query("temperature_celsius<-90 or temperature_celsius>60")))
print("\nData coverage:\n", df.count())

 Missing Values: None
Humidity anomalies: 0 | Temperature anomalies: 0

Data coverage:
 country                         88273
location_name                   88273
latitude                        88273
longitude                       88273
timezone                        88273
last_updated_epoch              88273
last_updated                    88273
temperature_celsius             88273
temperature_fahrenheit          88273
condition_text                  88273
wind_mph                        88273
wind_kph                        88273
wind_degree                     88273
wind_direction                  88273
pressure_mb                     88273
pressure_in                     88273
precip_mm                       88273
precip_in                       88273
humidity                        88273
cloud                           88273
feels_like_celsius              88273
feels_like_fahrenheit           88273
visibility_km                   88273
visibility_miles                88273
uv_index                        88273
gust_mph                        88273
gust_kph                        88273
air_quality_Carbon_Monoxide     88273
air_quality_Ozone               88273
air_quality_Nitrogen_dioxide    88273
air_quality_Sulphur_dioxide     88273
air_quality_PM2.5               88273
air_quality_PM10                88273
air_quality_us-epa-index        88273
air_quality_gb-defra-index      88273
sunrise                         88273
sunset                          88273
moonrise                        88273
moonset                         88273
moon_phase                      88273
moon_illumination               88273
dtype: int64

In [ ]:

print(" Missing values before cleaning:")
print(df.isna().sum()[df.isna().sum() > 0])
# Handling missing/inconsistent data
df.loc[(df["temperature_celsius"] < -50) | (df["temperature_celsius"] > 60), "temperature_celsius"] = None
df.fillna(df.mean(numeric_only=True), inplace=True)
df.fillna("Unknown", inplace=True)
print("\n Missing values after cleaning:")
print(df.isna().sum()[df.isna().sum() > 0])
print("\nCleaned Data (first 5 rows):")
print(df.head())

 Missing values before cleaning:
Series([], dtype: int64)

 Missing values after cleaning:
Series([], dtype: int64)

Cleaned Data (first 5 rows):
       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch        last_updated  temperature_celsius  \
0          1715849100 2024-05-16 13:15:00                 26.6
1          1715849100 2024-05-16 10:45:00                 19.0
2          1715849100 2024-05-16 09:45:00                 23.0
3          1715849100 2024-05-16 10:45:00                  6.3
4          1715849100 2024-05-16 09:45:00                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM10  \
0                    79.8  Partly Cloudy  ...              26.6
1                    66.2  Partly cloudy  ...               2.0
2                    73.4          Sunny  ...              18.4
3                    43.3  Light drizzle  ...               0.9
4                    78.8  Partly cloudy  ...             262.3

   air_quality_us-epa-index  air_quality_gb-defra-index   sunrise    sunset  \
0                         1                           1  04:50 AM  06:50 PM
1                         1                           1  05:21 AM  07:54 PM
2                         1                           1  05:40 AM  07:50 PM
3                         1                           1  06:31 AM  09:11 PM
4                         5                          10  06:12 AM  05:55 PM

   moonrise   moonset      moon_phase  moon_illumination  year_month
0  12:12 PM  01:11 AM  Waxing Gibbous                 55     2024-05
1  12:58 PM  02:14 AM  Waxing Gibbous                 55     2024-05
2  01:15 PM  02:14 AM  Waxing Gibbous                 55     2024-05
3  02:12 PM  03:31 AM  Waxing Gibbous                 55     2024-05
4  01:17 PM  12:38 AM  Waxing Gibbous                 55     2024-05

[5 rows x 42 columns]

In [ ]:

df["last_updated"] = pd.to_datetime(df["last_updated"], errors="coerce")
# Daily data
daily_data = df.copy()
print(daily_data.head())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch        last_updated  temperature_celsius  \
0          1715849100 2024-05-16 13:15:00                 26.6
1          1715849100 2024-05-16 10:45:00                 19.0
2          1715849100 2024-05-16 09:45:00                 23.0
3          1715849100 2024-05-16 10:45:00                  6.3
4          1715849100 2024-05-16 09:45:00                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                    79.8  Partly Cloudy  ...                8.4
1                    66.2  Partly cloudy  ...                1.1
2                    73.4          Sunny  ...               10.4
3                    43.3  Light drizzle  ...                0.7
4                    78.8  Partly cloudy  ...              183.4

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0              26.6                         1                          1
1               2.0                         1                          1
2              18.4                         1                          1
3               0.9                         1                          1
4             262.3                         5                         10

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous                 55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous                 55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous                 55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous                 55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous                 55

[5 rows x 41 columns]

In [ ]:
# Add year-month column
df["year_month"] = df["last_updated"].dt.to_period("M").astype(str)

# Monthly averages per country
monthly_data = (
    df.groupby(["country", "year_month"])
      .mean(numeric_only=True)
      .reset_index()
)

print(monthly_data.head())

       country year_month  latitude  longitude  last_updated_epoch  \
0  Afghanistan    2024-05     34.52      69.18        1.716478e+09
1  Afghanistan    2024-06     34.52      69.18        1.718503e+09
2  Afghanistan    2024-07     34.52      69.18        1.721101e+09
3  Afghanistan    2024-08     34.52      69.18        1.723811e+09
4  Afghanistan    2024-09     34.52      69.18        1.726442e+09

   temperature_celsius  temperature_fahrenheit   wind_mph   wind_kph  \
0            20.305882               68.523529   7.164706  11.517647
1            25.590000               78.043333  10.636667  17.110000
2            31.303448               88.362069  12.886207  20.731034
3            30.848387               87.538710  12.551613  20.196774
4            28.216667               82.783333   7.583333  12.223333

   wind_degree  ...   gust_kph  air_quality_Carbon_Monoxide  \
0   127.941176  ...  16.141176                  1424.094118
1   126.833333  ...  20.336667                  1481.570000
2   103.862069  ...  23.841379                   624.758621
3    57.709677  ...  23.238710                   605.025806
4    67.566667  ...  14.063333                   376.173333

   air_quality_Ozone  air_quality_Nitrogen_dioxide  \
0          77.452941                     16.400000
1          87.650000                     17.000000
2         119.327586                      4.700000
3         119.612903                      3.641935
4         138.046667                      2.523667

   air_quality_Sulphur_dioxide  air_quality_PM2.5  air_quality_PM10  \
0                     0.588235           7.894118         17.411765
1                     0.530000           7.380000         16.786667
2                     0.306897           9.065517         23.596552
3                     0.306452           9.638710         22.674194
4                    13.977000          20.996833         42.791667

   air_quality_us-epa-index  air_quality_gb-defra-index  moon_illumination
0                  1.000000                    1.117647          78.647059
1                  1.000000                    1.066667          49.800000
2                  1.068966                    1.137931          43.758621
3                  1.032258                    1.225806          45.548387
4                  1.666667                    2.366667          46.100000

[5 rows x 32 columns]